# Generated by Django 3.2.9 on 2021-11-07 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('statusId', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'BookingStatus',
            },
        ),
        migrations.CreateModel(
            name='ExperienceTags',
            fields=[
                ('exptagid', models.AutoField(primary_key=True, serialize=False)),
                ('exp_tag', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'ExperienceTags',
            },
        ),
        migrations.CreateModel(
            name='HotelInfo',
            fields=[
                ('hotelid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('location_street', models.CharField(blank=True, max_length=200, null=True)),
                ('location_city', models.CharField(blank=True, max_length=200, null=True)),
                ('location_country', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=200, null=True)),
                ('experiances_tags', models.ManyToManyField(to='app_nomand.ExperienceTags')),
            ],
            options={
                'db_table': 'HotelInfo',
            },
        ),
        migrations.CreateModel(
            name='LocationCountry',
            fields=[
                ('countryid', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'LocationCountry',
            },
        ),
        migrations.CreateModel(
            name='LocationCity',
            fields=[
                ('cityid', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_nomand.locationcountry')),
            ],
            options={
                'db_table': 'LocationCity',
            },
        ),
        migrations.CreateModel(
            name='HotelReservationItem',
            fields=[
                ('reservationItemId', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_item', models.CharField(blank=True, max_length=200, null=True)),
                ('priceinfo_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('priceinfo_lkr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_nomand.hotelinfo')),
            ],
            options={
                'db_table': 'HotelReservationItem',
            },
        ),
        migrations.CreateModel(
            name='HotelImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to='')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_nomand.hotelinfo')),
            ],
            options={
                'db_table': 'HotelImages',
            },
        ),
        migrations.CreateModel(
            name='HotelAmenities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_nomand.hotelinfo')),
            ],
            options={
                'db_table': 'HotelAmenities',
            },
        ),
        migrations.CreateModel(
            name='GuestInfo',
            fields=[
                ('guestid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contactNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_nomand.locationcountry')),
            ],
            options={
                'db_table': 'GuestInfo',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('expid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
                ('cover_image', models.ImageField(upload_to='')),
                ('exptag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_nomand.experiencetags')),
            ],
            options={
                'db_table': 'Experience',
            },
        ),
        migrations.CreateModel(
            name='BookingInfo',
            fields=[
                ('bookingid', models.AutoField(primary_key=True, serialize=False)),
                ('checkIn', models.DateTimeField(blank=True, null=True)),
                ('checkOut', models.DateTimeField(blank=True, null=True)),
                ('booking_type', models.CharField(blank=True, max_length=200, null=True)),
                ('is_paid', models.BooleanField(blank=True, null=True)),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_nomand.guestinfo')),
                ('reservationItem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_nomand.hotelreservationitem')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_nomand.bookingstatus')),
            ],
            options={
                'db_table': 'BookingInfo',
            },
        ),
    ]
