# Generated by Django 3.2.9 on 2021-11-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nomand', '0002_auto_20211108_0033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExperienceTags',
        ),
        migrations.AlterField(
            model_name='hotelinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
