# Generated by Django 3.2.9 on 2021-12-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='PageAdmin',
        ),
    ]
